@startuml packages
set namespaceSeparator none
package "flowly.core" as flowly.core {
}
package "flowly.core.attribute_item" as flowly.core.attribute_item {
}
package "flowly.core.base_item" as flowly.core.base_item {
}
package "flowly.core.main" as flowly.core.main {
}
package "flowly.core.node_graph" as flowly.core.node_graph {
}
package "flowly.core.node_item" as flowly.core.node_item {
}
package "flowly.core.operator_item" as flowly.core.operator_item {
}
flowly.core.attribute_item --> flowly.core.base_item
flowly.core.main --> flowly.core.node_graph
flowly.core.main --> flowly.core.node_item
flowly.core.node_graph --> flowly.core.attribute_item
flowly.core.node_item --> flowly.core.attribute_item
flowly.core.node_item --> flowly.core.base_item
flowly.core.node_item --> flowly.core.operator_item
flowly.core.operator_item --> flowly.core.base_item
flowly.core.attribute_item ..> flowly.core.node_item
flowly.core.main ..> flowly.core.base_item
flowly.core.node_graph ..> flowly.core.base_item
flowly.core.node_graph ..> flowly.core.node_item
flowly.core.operator_item ..> flowly.core.node_item
@enduml
